services:
  - type: web
    name: waste-management-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn Myproject.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: waste-management-db
          property: connectionString
      - key: FRONTEND_ORIGIN
        value: "https://abdullatif-1v8l.vercel.app"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://abdullatif-1v8l.vercel.app,https://abdullatif-ymyj.vercel.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://abdullatif-1v8l.vercel.app,https://abdullatif-ymyj.vercel.app"

databases:
  - name: waste-management-db
    plan: free
    databaseName: wastedb
    user: wastedb_user
